PORT=31001  # you probably want to change this

CFLAGS= -DPORT=$(PORT) -g -Wall 

testfiledata : testfiledata.o filedata.o
	gcc ${CFLAGS} -o $@ $^
    
%.o : %.c
	gcc ${CFLAGS} -c $<

clean: 
	rm *.o testfiledata
